### ISSUE TITLE
Support external URLs in icons

### ISSUE THREAD

**Issue by Stanzilla** [tumblr/webpack-web-app-manifest-plugin#7]
Hey there, I'd love to use direct links to a icons on a CDN but that does not seem supported?

**Comment by sirreal** [comment]
I don't believe that's supported right now. What did you have in mind? Part of the purpose of the plugin is to extract the icons URLs from the webpack bundle. Would you be providing icons in the configuration?

**Comment by sirreal** [comment]
I'm going to close this due to inactivity. I'd be happy to reopen and discuss.
